export const LISTINGMENUITEMS = [
    { value: "Create Listing Package", label: "Listing Package", customPrompt: "You will create a listing package for me based on the listing information provided. Included in the listing package: 1. Identify the homes unique selling features. 2. Research the neighborhood. 3. Rewrite the property description. 4. Create Facebook ad copy - use emojis in the copy. 5. Create quick google search ad content. 6. Create a quick SMS blast message. 7. Create listing flyer content based on information about the listing. 8. Create 3 yard sign call to actions to use. 9. Create a quick email newsletter about the property. Be organized and use markdown format. Each section should be detailed but not too long. Use emojis in the social marketing sections." },
    { value: "Write A Blog Post", label: "Blog Post", customPrompt: "Create a custom blog post about the listing and zip code without an introduction sentence. Be comprehensive and include information previously given to you. Use markdown with h1 sections, numbered points, and bullet points. Proceed step-by-step. After completion, ask me if I want to change the tone, content, or other aspects and follow my direction." },
    { value: "Compose An Email", label: "Email", customPrompt: "Compose an email about the listing with key features and zip code information without an introduction sentence. Make it friendly, informative, and unique. Use markdown with h1 sections, numbered points, and bullet points. Proceed step-by-step. After completion, ask me if I want to change the tone, content, or other aspects and follow my directions." },
    { value: "Create Facebook Ad Content", label: "Facebook Ad Content", customPrompt: "Create Facebook ad content for a specific listing to attract home buyers by highlighting key features and benefits. Use provided listing information for an engaging, informative ad. Display with campaign idea and  ad copy in markdown. Use emojis always. Proceed step-by-step, using only given data. Avoid fabricating open house times, area info, or listing details. After completion, ask me if I want changes or additions to the ad content." },
    { value: "Create a Video Tour Script", label: "Video Tour Script", customPrompt: "Create a video tour script for the selected listing using provided information. Highlight key property features and provide a comprehensive tour. Use engaging language, tone, and visually appealing content. Display in markdown with h1 sections, numbered points, and bullet points. Proceed step-by-step. After completion, ask me if I want changes or additions to the video tour script." },
    { value: "Create an Instagram Reel", label: "Reel Script", customPrompt: "Create a Reel for the selected listing using provided information. Highlight key property features and provide a comprehensive tour. Make sure to layout a full script for the entire reel. Respond as a script. After completion, ask me if I want changes or additions to the Instagram Reel." },
    { value: "Create SMS Message Content", label: "Text Message", customPrompt: "Create 2 SMS messages about the property given to you - do not ask for more information, use what you were provided. Each output from you has two parts: campaign title and the actual message. Display in markdown format. Use only provided data, keep messages under 160 characters. Proceed step-by-step. Always generate a first draft. After completion, ask me if I want changes or additions to the SMS messages." },
    { value: "Create Listicle", label: "Create Listicle", customPrompt: "You will create a listicle in markdown format about the selected listing. Choose at random any listicle between 5 and 8 items long. Afterwards, you will ask me if I want to have you generate a different one." },
];

export const AREAMENUITEMS = [
    { value: "Area Package", label: "Area Package", customPrompt: "An Area Package is a concise marketing collection of copy assets for a specific channels, featuring unique selling points, area stats, buyer profiles, and various content types like social media ads with emojis, search ads, SMS blasts, flyers, email newsletters, and blog posts. Write out the package content using a step-by-step approach with markdown formatting, it's organized and detailed and sometimes contains lists." },
    { value: "Create Facebook Ad Content", label: "Facebook Ad Content", customPrompt: "Create Facebook ad content to market the area given previously (if no area information was given, ask me to select from the dropdown on the left), using provided information on demographics, amenities, attractions, and available properties. Use emojis. Display in markdown format with the campaign idea as h1 and ad copy as regular text. Use only given data and avoid making up information. After completion, ask me if I want to make changes or additions to the ad content." },
    { value: "Create Reel script for the Area", label: "Instagram Reel", customPrompt: "Create a 15 second voice script to market are provided earlier, using information on market data. Also include known attractions, dining, and activities. Ensure engaging language, visual appeal, relevant hashtags, and a call to action. Display in script format. Use only given data and avoid making up information. After completion, ask me if I want to make changes or additions to the Reel." },
    { value: "Generate Marketing Plan", label: "Marketing Plan", customPrompt: "Create a marketing plan for a specific area, highlighting unique features and benefits. Ask me questions to gather necessary information for a quality, easy-to-follow plan. Use given data and display the plan in markdown format with H1 headings and bullet points. Take things step-by-step, use engaging language, and avoid making up information. After completion, ask me if I want to discuss any specific campaign further." },
    { value: "Create Blog Post", label: "Blog Post", customPrompt: "Create a custom blog post about a specific area, including local real estate market and demographics. Start directly with the blog content, using a light-hearted tone and highlighting unique features and benefits. Display the post in markdown format with H1 headings, bullet points, numbered lists, or regular text. Use given data and avoid making up information. After completion, ask me if I want to change the tone, content, or any other aspect of the blog." },
    { value: "Create Area Guide", label: "Area Guide", customPrompt: "Create a comprehensive guide for people looking to move to a specific area using provided information. Start directly with the guide content, including sections like hot spots, key data points, things to do, points of interest, and information about any listings I have in the area if you were given information about one. Display the guide in markdown format with H1 headings, numbered lists or bullet points, and H2 tags where applicable. Use engaging language and given data, avoiding making up information. After completion, ask me if I want to change the tone, content, or any other aspect of the area guide. Make sure to be conversational and use bullet points where necesssary, and paragraphs of information where necessary to give the overall feel of a guide." },
    { value: "Compose an Area Email", label: "Area Email", customPrompt: "Write an informative email about a specific area, including key features, statistics, and local real estate market information including any listing information you were given by me. Start directly with the email content and display it with a signature section based on my information. Use engaging language and provided data, avoiding making up information. After completion, ask me if I want to change the tone, content, or any other aspect of the email." },
    { value: "Create a Newsletter", label: "Newsletter", customPrompt: "A comprehensive newsletter is a concise, engaging, and accurate report for potential clients on a specific neighborhood, featuring key data, hot spots, activities, and provided listings. Write it by taking a step-by-step approach, formatted in markdown with titles and bullet points." },
    { value: "Create Text Messages", label: "Text Message", customPrompt: "Create 3 brief, informative, and unique SMS messages about a specific property or neighborhood for potential clients. Include key features, a call to action, and relevant information. Display in markdown format with a two-part structure: an h1 title for the campaign concept and the actual message as regular text. Use provided data and avoid making up information. Keep messages under 160 characters. Start directly with content and take a step-by-step approach. After completion, ask me if I want to make changes or additions to the SMS messages." },
    { value: "Create Listicle", label: "Create Listicle", customPrompt: "You will create a listicle in markdown format related to the area or areas like it in general. Choose at random any listicle between 5 and 8 items long. Afterwards, you will ask me if I want to have you generate a different one." },
];

export const FOLLOWUPMENUITEMS = [
    { value: "Generate a Quick Gameplan", label: "Quick Gameplan", customPrompt: "Create a quick follow-up gameplan tailored to a specific lead. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create a 1 Month Plan", label: "1 Month Plan", customPrompt: "Create a 1-month follow-up gameplan. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create a 3 Month Plan", label: "3 Month Plan", customPrompt: "Create a 3-month follow-up gameplan. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create listicle", label: "Create Listicle", customPrompt: "You will create a listicle in markdown format about home ownership, getting ready t sell your home, or anything real estate related. Be creative. Choose at random any listicle between 5 and 8 items long. Afterwards, you will ask me if I want to have you generate a different one." },
    { value: "Random Content", label: "Random Content", customPrompt: "Write a randomly generated interesting piece about home ownership, home selling, or home buying. Be creative, engaging and something that is useful or interesting for homeowners or homebuyers to read. Write in markdown format." },
    { value: "Create A Schedule", label: "Create A Schedule", customPrompt: "Create a long-term follow-up schedule in table format from day 1 to day 180. Columns should include day, follow-up channel, difficulty rating, budget, technical knowledge, and the full content for the follow-up. Be comprehensive and detailed in the content section." },
    { value: "Generate a Follow Up Table", label: "Follow Up Table", customPrompt: "Create a markdown table comparing various follow-up activities and their difficulty to implement. Columns should include channels, campaign types, deliverables, difficulty (1-10), experience needed, technical knowledge, and online tools. Each row should have one unique entry per column. Include multiple rows for the same channel if needed, and create 10 different rows." },
    { value: "Generate Objection Handling", label: "Objection Handling", customPrompt: "Create a markdown table comparing various objections I may encounter during lead follow-ups. Columns should include Objection, severity level, script to handle objection, and a follow-up question. Each row should have one unique entry per column. Follow NAR rules (e.g. ending the conversation if the objection is having another agent). Include 10 different rows of objections." },
];

export const PRELISTINGMENUITEMS = [
    { value: "Write Property Description", label: "Property Description", customPrompt: "Write a property description for the MLS based on the property information you were given. Do not use imagined information about the property or include last sales information. Make the description informational and interesting to potential buyers. Afterwards you must ask me if there are any additional pieces of information to add or omit." },
    { value: "Coming Soon", label: "Coming Soon Package", customPrompt: "Create content for a coming soon package consisting of various pieces of content to market a property before it hits the MLS. Think step by step. In the package you'll create content for a flyer, Social ad, a blog post, and a text message to let home owners and home buyers know about an upcoming property for sale. Do not just list the items. Create the content for each section as well in a convesrational tone. Give your output in markdown format." },
    { value: "Write a letter to the seller", label: "Seller's Letter", customPrompt: "Draft a personalized letter to the seller of the property given. It should be professional, introduce me as a premier agent in the area, and give some background on my brokerage. Ask any questions you need from me to make it personalized." },
    { value: "Check Market Stats", label: "Market Stats", customPrompt: "Provide market statistics for the area given. Think step by step. Give your output in markdown format." },
];