export const LISTINGMENUITEMS = [
    { value: "Create Listing Package", label: "Listing Package", customPrompt: "You will create a listing package for me based on the listing information provided. Included in the listing package: 1. Identify the homes unique selling features. 2. Research the neighborhood. 3. Rewrite the property description. 4. Create Facebook ad copy - use emojis. 5. Create Instagram copy - use emojis. 6. Create quick google search ad content. 7. Create a quick SMS blast message. 8. Create listing flyer content based on information about the listing. 9. Create 3 yard sign call to actions to use. 10. Create a quick email newsletter about the property. 11. Write a short blog post. Be organized and use markdown format where necessary. Each section should be detailed but not too long. Afterwards, let me know I can copy and paste this to a word document, and can also dive in deeper to any additional section for step by step instructions. Use emojis in the social marketing sections." },
    { value: "Write A Blog Post", label: "Blog Post", customPrompt: "Create a custom blog post about the listing and zip code without an introduction sentence. Be comprehensive and include information previously given to you. Use markdown with h1 sections, numbered points, and bullet points. Proceed step-by-step. After completion, ask me if I want to change the tone, content, or other aspects and follow my direction." },
    { value: "Compose An Email", label: "Email", customPrompt: "Compose an email about the listing with key features and zip code information without an introduction sentence. Make it friendly, informative, and unique. Use markdown with h1 sections, numbered points, and bullet points. Proceed step-by-step. After completion, ask me if I want to change the tone, content, or other aspects and follow my directions." },
    { value: "Create Facebook Ad Content", label: "Facebook Ad Content", customPrompt: "Create Facebook ad content for a specific listing to attract home buyers by highlighting key features and benefits. Use provided listing information for an engaging, informative ad. Display with h1 campaign idea and regular text for ad copy in markdown. Use emojis. Proceed step-by-step, using only given data. Avoid fabricating open house times, area info, or listing details. After completion, ask me if I want changes or additions to the ad content." },
    { value: "Create a Video Tour Script", label: "Video Tour Script", customPrompt: "Create a video tour script for the selected listing using provided information. Highlight key property features and provide a comprehensive tour. Use engaging language, tone, and visually appealing content. Display in markdown with h1 sections, numbered points, and bullet points. Proceed step-by-step. After completion, ask me if I want changes or additions to the video tour script." },
    { value: "Create an Instagram Reel", label: "Reel Script", customPrompt: "Create an Instagram Reel for the selected listing using provided information. Highlight key property features and provide a comprehensive tour. Make sure to layout a full script for the entire reel. Display in markdown with h1 sections, numbered points, and bullet points. Proceed step-by-step. After completion, ask me if I want changes or additions to the Instagram Reel." },
    { value: "Create SMS Message Content", label: "Text Message", customPrompt: "Create 5 SMS messages about a specific property or neighborhood. Keep messages brief, informative, and unique. Include key features, a call to action, and relevant information. Each message has two parts: Part 1 (h1) - campaign title; Part 2 - the actual message. Display in markdown format. Use only provided data, keep messages under 160 characters. Proceed step-by-step. After completion, ask me if I want changes or additions to the SMS messages." },
    { value: "Create Marketing Matrix", label: "Marketing Matrix", customPrompt: "You will create a Marketing Matrix table in markdown or ascii format with various different campaign ideas, channel, scale from 1-10 of difficulty, experience needing, technical knowledge needed, budget required, any online tools needed. You can have multiple channels in some cases but try to keep everything as organized as possible. Always produce 15 rows. Afterwards, ask me if there is a particular campaign I would like to go into more detail on." },
];

export const AREAMENUITEMS = [
    { value: "Area Package", label: "Area Package", customPrompt: "An Area Package is a concise marketing collection of copy assets for a specific channels, featuring unique selling points, area stats, buyer profiles, and various content types like social media ads with emojis, search ads, SMS blasts, flyers, email newsletters, and blog posts. Develop using a step-by-step approach with markdown formatting, it's organized and detailed and sometimes contains lists." },
    { value: "Create Facebook Ad Content", label: "Facebook Ad Content", customPrompt: "Create Facebook ad content to market the area given previously (if no area information was given, ask me to select from the dropdown on the left), using provided information on demographics, amenities, attractions, and available properties. Use emojis. Display in markdown format with the campaign idea as h1 and ad copy as regular text. Use only given data and avoid making up information. After completion, ask me if I want to make changes or additions to the ad content." },
    { value: "Create Reel script for the Area", label: "Instagram Reel", customPrompt: "Create an Instagram Reel to market the selected area, using provided information on location features, attractions, dining, and activities. Ensure engaging language, visual appeal, relevant hashtags, and a call to action. Display in markdown format with h1 for sections, and provide step-by-step instructions for content, script, and layout. Use only given data and avoid making up information. After completion, ask me if I want to make changes or additions to the Reel." },
    { value: "Generate Marketing Plan", label: "Marketing Plan", customPrompt: "Create a marketing plan for a specific area, highlighting unique features and benefits. Ask me questions to gather necessary information for a quality, easy-to-follow plan. Use given data and display the plan in markdown format with H1 headings and bullet points. Take things step-by-step, use engaging language, and avoid making up information. After completion, ask me if I want to discuss any specific campaign further." },
    { value: "Create Blog Post", label: "Blog Post", customPrompt: "Create a custom blog post about a specific area, including local real estate market and demographics. Start directly with the blog content, using a light-hearted tone and highlighting unique features and benefits. Display the post in markdown format with H1 headings, bullet points, numbered lists, or regular text. Use given data and avoid making up information. After completion, ask me if I want to change the tone, content, or any other aspect of the blog." },
    { value: "Create Area Guide", label: "Area Guide", customPrompt: "Create a comprehensive guide for people looking to move to a specific area using provided information. Start directly with the guide content, including sections like hot spots, key data points, things to do, points of interest, and information about any listings I have in the area if you were given information about one. Display the guide in markdown format with H1 headings, numbered lists or bullet points, and H2 tags where applicable. Use engaging language and given data, avoiding making up information. After completion, ask me if I want to change the tone, content, or any other aspect of the area guide. Make sure to be conversational and use bullet points where necesssary, and paragraphs of information where necessary to give the overall feel of a guide." },
    { value: "Compose an Area Email", label: "Area Email", customPrompt: "Write an informative email about a specific area, including key features, statistics, and local real estate market information including any listing information you were given by me. Start directly with the email content and display it with a signature section based on my information. Use engaging language and provided data, avoiding making up information. After completion, ask me if I want to change the tone, content, or any other aspect of the email." },
    { value: "Create a Newsletter", label: "Newsletter", customPrompt: "A comprehensive newsletter is a concise, engaging, and accurate report for potential clients on a specific neighborhood, featuring key data, hot spots, activities, and provided listings. It uses a step-by-step approach, formatted in markdown with titles and bullet points." },
    { value: "Create Text Messages", label: "Text Message", customPrompt: "Create 5 brief, informative, and unique SMS messages about a specific property or neighborhood for potential clients. Include key features, a call to action, and relevant information. Display in markdown format with a two-part structure: an h1 title for the campaign concept and the actual message as regular text. Use provided data and avoid making up information. Keep messages under 160 characters. Start directly with content and take a step-by-step approach. After completion, ask me if I want to make changes or additions to the SMS messages." },
    { value: "Generate Marketing Matrix", label: "Marketing Matrix", customPrompt: "Create a 10-row Marketing Matrix table in markdown or ASCII format, including campaign ideas, channel, difficulty (1-10), experience needed, technical knowledge needed, budget, and online tools. Maintain organization and allow multiple channels in some cases. After completion, ask me if I want more detail on a specific campaign. Never recommend Zillow or other data sources, and always suggest using Paisley (yourself) for content creation. But do not reference yourself in your content response." },
];

export const FOLLOWUPMENUITEMS = [
    { value: "Generate a Quick Gameplan", label: "Quick Gameplan", customPrompt: "Create a quick follow-up gameplan tailored to a specific lead. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create a 1 Month Plan", label: "1 Month Plan", customPrompt: "Create a 1-month follow-up gameplan. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create a 3 Month Plan", label: "3 Month Plan", customPrompt: "Create a 3-month follow-up gameplan. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create a 6 Month Plan", label: "6 Month Plan", customPrompt: "Create a 6-month follow-up gameplan. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create a 9 Month Plan", label: "9 Month Plan", customPrompt: "Create a 9-month follow-up gameplan. Ask relevant questions about lead information, lead generation, process stage, deliverables, and other essential details. Create an organized, comprehensive plan outline using markdown format. Afterward, ask which section to elaborate on and provide comprehensive, detailed responses. Utilize information from prior questioning and given data." },
    { value: "Create A Schedule", label: "Create A Schedule", customPrompt: "Create a long-term follow-up schedule in table format from day 1 to day 180. Columns should include day, follow-up channel, difficulty rating, budget, technical knowledge, and the full content for the follow-up. Be comprehensive and detailed in the content section." },
    { value: "Generate a Follow Up Table", label: "Follow Up Table", customPrompt: "Create a markdown table comparing various follow-up activities and their difficulty to implement. Columns should include channels, campaign types, deliverables, difficulty (1-10), experience needed, technical knowledge, and online tools. Each row should have one unique entry per column. Include multiple rows for the same channel if needed, and create 20 different rows." },
    { value: "Generate Objection Handling", label: "Objection Handling", customPrompt: "Create a markdown table comparing various objections I may encounter during lead follow-ups. Columns should include Objection, severity level, script to handle objection, and a follow-up question. Each row should have one unique entry per column. Follow NAR rules (e.g. ending the conversation if the objection is having another agent). Include 15 different rows of objections." },
];